project:
  type: website
  output-dir: docs

website:
  title: "Inter R4SS"
  navbar:
    background: primary
    right:
      - text: "Home"
        href: index.qmd
      - text: "Details"
        menu:
          - text: "Instructor"
            href: ./Details/instructor.qmd
          - text: "Assistant"
            href: ./Details/assistant.qmd
          - text: "Schedule"
            href: ./Details/schedule.qmd
          - text: "Recordings"
            href: ./Details/recordings.qmd
      - text: "Day 1"
        menu:
          - text: "Day 1A Materials"
            href: ./Day1/day1A.qmd
          - text: "Day 1B Materials"
            href: ./Day1/day1B.qmd
      - text: "Day 2"
        menu:
          - text: "Day 2A Materials"
            href: ./Day2/day2A.qmd
          - text: "Day 2B Materials"
            href: ./Day2/day2B.qmd
      - text: "Day 3"
        menu:
          - text: "Day 3A Materials"
            href: ./Day3/day3A.qmd
          - text: "Day 2B Materials"
            href: ./Day3/day3B.qmd
  page-footer: "Copyright 2023 &copy; Jeffrey Girard"

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true

execute:
  freeze: auto
